In [1]:
import numpy as np

In [2]:
arr1=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])


arr2=np.array([[9,8,7],
             [6,5,4],
             [3,2,1]])

In [3]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [6]:
arr1+arr2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [7]:
arr1-arr2

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [8]:
arr1 * arr2

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [10]:
#dot products
arr1.dot(arr2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [11]:
arr=np.array([1,2,3,4,5])

In [12]:
arr[:]

array([1, 2, 3, 4, 5])

In [13]:
arr[:3]

array([1, 2, 3])

In [14]:
arr1=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

In [16]:
arr1[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
#row:column

arr1[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr1[:,:1]

array([[1],
       [4],
       [7]])

In [20]:
arr1[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [22]:
arr1[:1,:]

array([[1, 2, 3]])

In [23]:
arr1[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
#from two columns 1 column (1=removing 1st columns and remains 2nd column)

arr1[:, 1:2]

array([[2],
       [5],
       [8]])

In [33]:
#to pick 5, between 2 rows 1st row removed and between 2 columns 1st column removed
arr1[1:2,1:2]

array([[5]])

array([], shape=(0, 0), dtype=int64)