In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6])

In [3]:
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
arr+1

array([2, 3, 4, 5, 6, 7])

In [5]:
arr-1

array([0, 1, 2, 3, 4, 5])

In [6]:
arr * 5

array([ 5, 10, 15, 20, 25, 30])

In [7]:
arr / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [8]:
arr % 2

array([1, 0, 1, 0, 1, 0])

In [9]:
arr ** 2

array([ 1,  4,  9, 16, 25, 36])

In [11]:
arr ** 3

array([  1,   8,  27,  64, 125, 216])

In [12]:
arr

array([1, 2, 3, 4, 5, 6])

In [13]:
arr+=1

In [14]:
arr

array([2, 3, 4, 5, 6, 7])

In [15]:
arr *= 4

In [16]:
arr

array([ 8, 12, 16, 20, 24, 28])

In [17]:
arr.max()

28

In [18]:
arr.min()

8

In [19]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [20]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
#finding the max element inside this 2d array row and column wise

arr.max(axis=0)  #column wise max


array([7, 8, 9])

In [27]:
arr.max(axis=1)  #row wise max

array([3, 6, 9])

In [28]:
arr.min(axis=0)  #column wise min

array([1, 2, 3])

In [24]:
arr.min(axis=1)  #row wise min

array([1, 4, 7])

In [30]:
arr.sum()

45