In [3]:
import numpy as np

In [4]:
#a 2D array
arr=np.array([[7,3,2,4,9],[6,7,5,2,7],[9,2,5,7,2]])

In [6]:
arr

array([[7, 3, 2, 4, 9],
       [6, 7, 5, 2, 7],
       [9, 2, 5, 7, 2]])

In [7]:
#axis=1(sort array row wise) and axis=0 (for column wise)
np.sort(arr, axis=1, kind='quicksort')

array([[2, 3, 4, 7, 9],
       [2, 5, 6, 7, 7],
       [2, 2, 5, 7, 9]])

In [8]:
np.sort(arr, axis=0, kind='quicksort')

array([[6, 2, 2, 2, 2],
       [7, 3, 5, 4, 7],
       [9, 7, 5, 7, 9]])