In [1]:
import numpy as np

In [3]:
arr1=np.array([[1,2,3,4],[6,7,4,9]])
arr2=np.array([[4,3,5,7],[3,7,2,3]])

In [5]:
#concatenating them horizontally and vertically
#vstack=vertically concatenating

np.vstack((arr1,arr2))

array([[1, 2, 3, 4],
       [6, 7, 4, 9],
       [4, 3, 5, 7],
       [3, 7, 2, 3]])

In [6]:
np.hstack((arr1,arr2))  #horizontally concatenating

array([[1, 2, 3, 4, 4, 3, 5, 7],
       [6, 7, 4, 9, 3, 7, 2, 3]])

the reverse operation can also be performed i.e np.hstack((arr2,arr1))

In [7]:
np.concatenate((arr1,arr2),axis=0)

array([[1, 2, 3, 4],
       [6, 7, 4, 9],
       [4, 3, 5, 7],
       [3, 7, 2, 3]])

In [8]:
np.concatenate((arr1,arr2),axis=1)

array([[1, 2, 3, 4, 4, 3, 5, 7],
       [6, 7, 4, 9, 3, 7, 2, 3]])

In [9]:
#splitting the array

arr=np.concatenate((arr1,arr2),axis=0)


In [10]:
arr

array([[1, 2, 3, 4],
       [6, 7, 4, 9],
       [4, 3, 5, 7],
       [3, 7, 2, 3]])

In [12]:
np.hsplit(arr,2)   #2 is for splitting it into two halfs, hsplit=horizontal

[array([[1, 2],
        [6, 7],
        [4, 3],
        [3, 7]]),
 array([[3, 4],
        [4, 9],
        [5, 7],
        [2, 3]])]

In [14]:
np.vsplit(arr,2)  #vsplit=vertical

[array([[1, 2, 3, 4],
        [6, 7, 4, 9]]),
 array([[4, 3, 5, 7],
        [3, 7, 2, 3]])]