In [5]:
import numpy as np

In [6]:
arr=np.array([1,2,3,4,5,6,7,8])

In [7]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
arr[0]

1

In [11]:
arr[ 3: ]

array([4, 5, 6, 7, 8])

In [15]:
arr[ : -2]

array([1, 2, 3, 4, 5, 6])

In [16]:
arr[3:-3]

array([4, 5])

In [18]:
arr=np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])

In [19]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [20]:
arr[ : , : ]

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [21]:
arr[ : -2, :-2 ]  #arr[ row:row , col:col]

array([[1, 2],
       [5, 6]])

In [22]:
arr[ 2: , 2: ]

array([[6, 5],
       [2, 1]])

In [23]:
arr[1,1]

6

In [24]:
arr[2,3]

5

In [25]:
arr[2,2]

6

In [26]:
#cropping

arr[ 1:, 1:]

array([[6, 7, 8],
       [7, 6, 5],
       [3, 2, 1]])