In [2]:
!pip install numpy

In [5]:
import numpy as np

In [7]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [8]:
lst=[1,2,3]

In [9]:
lst

[1, 2, 3]

In [10]:
type(lst)

list

Converting list into an array

In [11]:
arr=np.array(lst)

In [12]:
arr

array([1, 2, 3])

In [15]:
# ndarray i.e n dimensional array
type(arr)

numpy.ndarray

In [14]:
# checking the dimension of the array

arr.ndim

1

In [17]:
# for 2nd dimension array

lst1=[[1,2,3],[4,5,6]]

In [18]:
arr2=np.array(lst1)

In [20]:
lst1

[[1, 2, 3], [4, 5, 6]]

In [21]:
arr2.ndim

2

In [22]:
# shape of array  #two rows three columns

arr2.shape

(2, 3)

In [23]:
arr2.size

6

In [24]:
arr2.dtype

dtype('int64')

In [25]:
#generating an array of given row x column

zeros=np.zeros((5,5))

In [26]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
ones=np.ones((4,8))

In [29]:
ones

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])