In [1]:
import numpy as np

In [3]:
np.random.random((3,3))

array([[0.52800868, 0.10129157, 0.13311902],
       [0.57543749, 0.70741601, 0.26731116],
       [0.23417787, 0.04530464, 0.71676807]])

In [6]:
np.random.random((3,3))

array([[0.8152962 , 0.41138913, 0.07244697],
       [0.21023482, 0.37103143, 0.76262912],
       [0.15861951, 0.34174681, 0.44611411]])

In [7]:
np.random.random()

0.2484083192856773

In [5]:
if np.random.random() > 0.5:
  print("run the function")
else:
  print("dont run the function")

run the function


In [13]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
#equal distance  #(starting,difference b/w numbers, ending)
np.linspace(1,2,100)

array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

In [22]:
arr=np.random.random((4,3))

In [23]:
arr

array([[0.79564914, 0.58765145, 0.72042606],
       [0.0478516 , 0.2612333 , 0.85889853],
       [0.89014598, 0.91334471, 0.99459989],
       [0.73435806, 0.49004842, 0.69511833]])

if reshaping an array from size (3,4) always remember the new value row*col should be equal to new size of array.

i.e (3,4)=(4,3)=(6,2)=(12,1)=(2,6)=(1,12)

In [28]:
arr = np.reshape(arr, (3,4))

In [30]:
arr

array([[0.79564914, 0.58765145, 0.72042606, 0.0478516 ],
       [0.2612333 , 0.85889853, 0.89014598, 0.91334471],
       [0.99459989, 0.73435806, 0.49004842, 0.69511833]])

In [31]:
#changes any dimension array to 1 dimension array
arr.flatten()

array([0.79564914, 0.58765145, 0.72042606, 0.0478516 , 0.2612333 ,
       0.85889853, 0.89014598, 0.91334471, 0.99459989, 0.73435806,
       0.49004842, 0.69511833])